Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_9_FE, pull requests merged in 2024-03, with the labels that each got.

#20 ✨ feat : 채팅방 구현
  assets/icons/back_black.svg
  lib/bindings/root_binding.dart
  lib/models/message/message_state.dart
  lib/services/user_service.dart
  lib/utilities/app_pages.dart
  lib/utilities/app_routes.dart
  lib/viewModels/home/doginfo_viewmodel.dart
  lib/viewModels/message/message_viewmodel.dart
  lib/viewModels/root/root_viewmodel.dart
  lib/views/chat/chat_screen.dart
  lib/views/home/doginfo_screen.dart
  lib/views/home/home_screen.dart
  lib/views/message/message_screen.dart
  lib/views/root/root_screen.dart
  lib/views/widget/adoption/Question.dart
  lib/views/widget/adoption/Question2.dart
  lib/views/widget/privacy/privacy_consent_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#26 ✨ feat : 공고 등록 스크린 구현
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/Info.plist
  lib/bindings/root_binding.dart
  lib/models/home/post_state.dart
  lib/utilities/font_system.dart
  lib/viewModels/home/post_viewmodel.dart
  lib/views/home/post_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#30 ✨ feat : 회원가입 및 selectMT 스크린 구현, 로그린/회원가입 api 연동
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/models/login/sign_state.dart
  lib/services/login_service.dart
  lib/services/sign_service.dart
  lib/utilities/font_system.dart
  lib/viewModels/login/signin_viewmodel.dart
  lib/views/login/login_screen.dart
  lib/views/login/selectmt_screen.dart
  lib/views/login/signin_screen.dart
  lib/views/widget/adoption/Question.dart
  pubspec.lock
Labels: feature

#35 ⚒️Fix: 로그인 api 연동 수정 및 다른 api(공고, 좋아요, 마이페이지) 연동 준비
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/main.dart
  lib/providers/AuthController.dart
  lib/services/login_service.dart
  lib/services/user_service.dart
  lib/utilities/app_pages.dart
  lib/viewModels/chat/chat_viewmodel.dart
  lib/viewModels/like/like_viewmodel.dart
  lib/viewModels/my/my_viewmodel.dart
  lib/views/like/like_screen.dart
  lib/views/login/loading_screen.dart
  lib/views/login/login_screen.dart
  lib/views/my/my_screen.dart
  lib/views/root/root_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#38 ✨feat : 메인화면, 좋아요 화면 api 연동
  lib/services/login_service.dart
  lib/services/user_service.dart
  lib/viewModels/like/like_viewmodel.dart
Labels: feature

#41 ✨ feat : 공고 등록 API 연동 완료
  lib/models/home/post_state.dart
  lib/services/post_service.dart
  lib/viewModels/home/post_viewmodel.dart
  lib/views/home/post_screen.dart
Labels: feature

#46 ✨ feat: 입양 신청 API 연동 완료
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/models/privacy/privacy_state.dart
  lib/services/privacy_service.dart
  lib/services/userpreferences_service.dart
  lib/utilities/font_system.dart
  lib/viewModels/privacy/privacy_viewmodel.dart
  lib/views/login/loading_screen.dart
  lib/views/message/message_screen.dart
  lib/views/widget/adoption/Question.dart
  lib/views/widget/adoption/Question2.dart
  lib/views/widget/privacy/hand_sign.dart
  lib/views/widget/privacy/privacy_consent_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#49 ✨ feat: 입양 신청/공고 페이지 service 수정, 마이페이지 api 연동 완료
  lib/models/my/my_state.dart
  lib/services/post_service.dart
  lib/services/privacy_service.dart
  lib/services/userpreferences_service.dart
  lib/viewModels/home/post_viewmodel.dart
  lib/viewModels/my/my_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/home/post_screen.dart
  lib/views/my/my_screen.dart
  lib/views/widget/adoption/Question2.dart
Labels: feature

#53 ✨ feat: 랜덤으로 대화하기 버튼 눌렀을 때 랜덤으로 PostId 설정하기
  lib/services/user_service.dart
  lib/services/userpreferences_service.dart
  lib/viewModels/message/message_viewmodel.dart
  lib/views/chat/chat_screen.dart
  lib/views/home/doginfo_screen.dart
Labels: feature

#56 ⚒️✨ fix, feat: 홈 화면 이름 연동으로 바꾸기, 입양 신청 딜레이 수정, 공고 스크린 메인이랑 잇기
  lib/services/login_service.dart
  lib/services/user_service.dart
  lib/views/home/home_screen.dart
  lib/views/home/post_screen.dart
  lib/views/root/root_screen.dart
  lib/views/widget/adoption/Question.dart
Labels: feature, fix

#60 ⚒️ fix : 회원가입 뷰 개선, 무한 스크롤 고치기
  android/app/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/services/post_service.dart
  lib/services/user_service.dart
  lib/services/userpreferences_service.dart
  lib/utilities/font_system.dart
  lib/views/home/home_screen.dart
  lib/views/login/signin_screen.dart
  pubspec.lock
Labels: fix
