Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_9_FE, pull requests merged in 2024-07, with the labels that each got.

#72 ⚒️ fix: 입양신청서 스크린 리팩토링
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/viewModels/privacy/privacy_viewmodel.dart
  lib/views/login/login_screen.dart
  lib/views/message/message_screen.dart
  lib/views/privacy/adoption_screen.dart
  lib/views/widget/adoption/Question2.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#74 ✨ feat: 카카오톡 소셜 로그인 기능 추가
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/main.dart
  lib/viewModels/login/login_viewmodel.dart
  lib/views/login/login_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#75 ✨ feat: 애플로그인 추가 & 홈화면 검색기능 추가
  android/app/src/profile/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/AppDelegate.swift
  lib/main.dart
  lib/services/login_service.dart
  lib/services/userpreferences_service.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/login/login_viewmodel.dart
  lib/viewModels/message/message_viewmodel.dart
  lib/viewModels/my/my_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/login/login_screen.dart
  lib/views/message/message_screen.dart
  lib/views/my/my_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feature

#77 ✨ feat: 메인화면 & 좋아요 토큰 추가
  lib/services/like_service.dart
  lib/services/login_service.dart
  lib/services/user_service.dart
  lib/viewModels/home/home_viewmodel.dart
  lib/viewModels/login/login_viewmodel.dart
  lib/views/login/login_screen.dart
Labels: feature, fix

#79 ⚒️ fix: 마이페이지 api, 스크린 url, 바텀네비게이션 수정
  lib/bindings/root_binding.dart
  lib/main.dart
  lib/services/chat_service.dart
  lib/services/like_service.dart
  lib/services/login_service.dart
  lib/services/my_service.dart
  lib/services/post_service.dart
  lib/services/privacy_service.dart
  lib/services/sign_service.dart
  lib/services/user_service.dart
  lib/viewModels/home/post_viewmodel.dart
  lib/viewModels/my/my_viewmodel.dart
  lib/viewModels/root/root_viewmodel.dart
  lib/views/home/home_screen.dart
  lib/views/home/post_screen.dart
  lib/views/root/custom_bottom_navigation_bar.dart
  lib/views/root/root_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: fix

#80 fix: 주소 사이트 안열리는 문제 해결
  ios/Runner/Info.plist
  pubspec.lock
  pubspec.yaml
Labels: fix

#82 ⚒️ fix: v1 구글 플레이 출시 전 최종 수정
  assets/images/login/kakao.png
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/models/home/dog_state.dart
  lib/models/message/message_state.dart
  lib/services/chat_service.dart
  lib/services/my_service.dart
  lib/services/sign_service.dart
  lib/services/user_service.dart
  lib/services/userpreferences_service.dart
  lib/utilities/font_system.dart
  lib/viewModels/chat/chat_viewmodel.dart
  lib/viewModels/home/doginfo_viewmodel.dart
  lib/viewModels/login/login_viewmodel.dart
  lib/viewModels/login/signin_viewmodel.dart
  lib/viewModels/message/message_viewmodel.dart
  lib/viewModels/my/my_viewmodel.dart
  lib/views/base/base_screen.dart
  lib/views/chat/chat_screen.dart
  lib/views/home/doginfo_screen.dart
  lib/views/home/home_screen.dart
  lib/views/login/loading_screen.dart
  lib/views/login/login_screen.dart
  lib/views/login/selectmt_screen.dart
  lib/views/login/signin_screen.dart
  lib/views/message/message_screen.dart
  lib/views/my/my_screen.dart
  lib/views/privacy/adoption_screen.dart
  lib/views/privacy/privacy_consent_screen.dart
  lib/views/privacy/regulatory_notice_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: fix
